{% set name = "jupyter_kernel_gateway" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 900690c4c0e796867355468d685f7fa1cf3c7775d08e871c157f77d65fbd6d7f

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - jupyter-kernelgateway = kernel_gateway:launch_instance

requirements:
  host:
    - python
    - hatchling >=1.5
    - pip
  run:
    - python
    - jupyter_client >=8.6
    - jupyter_core >=5.7
    - jupyter_server >=2.12
    - requests >=2.31
    - tornado >=6.4
    - traitlets >=5.14.1

test:
  source_files:
    - pyproject.toml
    - tests/
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-jupyter
    - ipykernel
  imports:
    - kernel_gateway
    - kernel_gateway.base
    - kernel_gateway.jupyter_websocket
    - kernel_gateway.notebook_http
    - kernel_gateway.notebook_http.cell
    - kernel_gateway.notebook_http.swagger
    - kernel_gateway.services
    - kernel_gateway.services.kernels
    - kernel_gateway.services.kernelspecs
    - kernel_gateway.services.sessions
  commands:
    - pip check
    - jupyter-kernelgateway --help
    - jupyter kernelgateway --help
    - pytest -vv

about:
  home: https://github.com/jupyter-server/kernel_gateway
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: Jupyter Kernel Gateway
  description: |
    Jupyter Kernel Gateway is a web server that supports different mechanisms for spawning 
    and communicating with Jupyter kernels. 
  doc_url: https://jupyter-kernel-gateway.readthedocs.io
  dev_url: https://github.com/jupyter-server/kernel_gateway

extra:
  recipe-maintainers:
    - parente
    - lresende
    - kevin-bates
