{% set version = "2.1.0" %}
{% set sha256 = "7fb26c04e1cd16ddbf9184a4cb0b74e90031b72b48f1c659e22ecaa8b49a95ce" %}

package:
  name: jupyter_kernel_gateway
  version: {{ version }}

source:
  fn: jupyter-kernel-gateway-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_kernel_gateway/jupyter_kernel_gateway-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-kernelgateway = kernel_gateway:launch_instance

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - jupyter_client >=4.2.0
    - jupyter_core >=4.0
    - notebook >=5.0.0
    - traitlets >=4.2.0
    - requests >=2.7
    - tornado >=4.2.0

test:
  imports:
    - kernel_gateway
    - kernel_gateway.base
    - kernel_gateway.jupyter_websocket
    - kernel_gateway.notebook_http
    - kernel_gateway.notebook_http.cell
    - kernel_gateway.notebook_http.swagger
    - kernel_gateway.services
    - kernel_gateway.services.kernels
    - kernel_gateway.services.kernelspecs
    - kernel_gateway.services.sessions
  commands:
    - jupyter-kernelgateway --help
    - jupyter kernelgateway --help

about:
  home: http://github.com/jupyter/kernel_gateway
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Jupyter Kernel Gateway
  doc_url: https://jupyter-kernel-gateway.readthedocs.io
  dev_url: https://github.com/jupyter/kernel_gateway

extra:
  recipe-maintainers:
    - parente
    - lresende
    - kevin-bates
