{% set name = "jupyter_kernel_gateway" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 900690c4c0e796867355468d685f7fa1cf3c7775d08e871c157f77d65fbd6d7f

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-kernelgateway = kernel_gateway:launch_instance

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - jupyter_client >=5.2.0,<8.0
    - jupyter_core >=4.4.0
    - notebook >=5.7.6,<7.0
    - traitlets >=4.2.0
    - requests >=2.7,<3.0
    - tornado >=4.2.0

test:
  requires:
    - pip
  imports:
    - kernel_gateway
    - kernel_gateway.base
    - kernel_gateway.jupyter_websocket
    - kernel_gateway.notebook_http
    - kernel_gateway.notebook_http.cell
    - kernel_gateway.notebook_http.swagger
    - kernel_gateway.services
    - kernel_gateway.services.kernels
    - kernel_gateway.services.kernelspecs
    - kernel_gateway.services.sessions
  commands:
    - pip check
    - jupyter-kernelgateway --help
    - jupyter kernelgateway --help

about:
  home: https://github.com/jupyter-server/kernel_gateway
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: Jupyter Kernel Gateway
  description: |
    Jupyter Kernel Gateway is a web server that supports different mechanisms for spawning
    and communicating with Jupyter kernels.
  doc_url: https://jupyter-kernel-gateway.readthedocs.io
  dev_url: https://github.com/jupyter-server/kernel_gateway

extra:
  recipe-maintainers:
    - parente
    - lresende
    - kevin-bates