{% set version = "2.5.1" %}
{% set sha256 = "1d40df18e1c5a346faf44716573dfd531343936bf479cb05e9391dbe28b90779" %}

package:
  name: jupyter_kernel_gateway
  version: {{ version }}

source:
  fn: jupyter-kernel-gateway-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_kernel_gateway/jupyter_kernel_gateway-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - jupyter-kernelgateway = kernel_gateway:launch_instance

requirements:
  host:
    - python
    - setuptools
    - wheel
  run:
    - python
    - jupyter_client >=5.2.0
    - jupyter_core >=4.4.0
    - notebook >=5.7.6,<7.0
    - traitlets >=4.2.0
    - requests >=2.7,<3.0
    - tornado >=4.2.0

test:
  imports:
    - kernel_gateway
    - kernel_gateway.base
    - kernel_gateway.jupyter_websocket
    - kernel_gateway.notebook_http
    - kernel_gateway.notebook_http.cell
    - kernel_gateway.notebook_http.swagger
    - kernel_gateway.services
    - kernel_gateway.services.kernels
    - kernel_gateway.services.kernelspecs
    - kernel_gateway.services.sessions
  commands:
    - jupyter-kernelgateway --help
    - jupyter kernelgateway --help

about:
  home: https://github.com/jupyter/kernel_gateway
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  license_url: https://opensource.org/licenses/BSD-3-Clause
  summary: Jupyter Kernel Gateway
  description: |
    Jupyter Kernel Gateway is a web server that provides headless access to Jupyter kernels.
  doc_url: https://jupyter-kernel-gateway.readthedocs.io
  doc_source_url: https://github.com/jupyter-server/kernel_gateway/blob/master/docs/source/index.rst
  dev_url: https://github.com/jupyter/kernel_gateway

extra:
  recipe-maintainers:
    - parente
    - lresende
    - kevin-bates
  skip-lints:
    - missing_license_url
    - missing_doc_source_url
