travis:
  secure:
    BINSTAR_TOKEN: BSJMHxAVf6bKw1e1k+2eObMP8gMdJfgEmObkW3WrKe/7T5s5E357rbP1gIFBj8RTJNdLCMa7UPtimzHdZor5b89wPszkjh7DUuyiqciGrd3SL4WHYyQOlMeE4OJKyjjRz1u2uJ5AwJEHyvxfHarmqVd5RT5Q2BGuEjkYVkOdvlLhxRJft3Gzr3kjNiJOYlfZJIM6Q5sZb5fYjfALuUvTli6zogLwrkbBMn6/HgC6Dm0T8fPvkoxU4B7k5fY6Rpzjr9f5DjAttC0LbtOJSAYbKbTVg7Gfny4BfFR+KoWlG922t8It0kRbOUfimVWOhgiXaGLaAnq9aYcI1hHsqE47Hb+8xKqqBGYvXldmvhpdxxnCHwhGFMs5fLxNsgnsFi1MwZOphvsZoEtq+qmveFQSUkBZpTW6kAuJK3LxGSbpYB7+0PNdFl2BBfMYvTd27gy1LBAoY40a+XdUze73zVQ/XiZb4jatYAsm0dpXvUiznyYE6ZVkbS42UFOHYD7gpAInUgF+i69O0ESZf05Nj1UlkKCa5aoW65IfWQxkeJgGYP9lVNDIcdYDUZP1hnggf2HfWtj4m5M7uIWFC0Cp7l8FvB3h/F+qZfbvDftymLoOn8Zb7aYzymtH6rJNcFq6WE5w6HfHxEUS1Qfw5Pzwx+CpLKZuVfmBK2RvlofCSkDa/d0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
