travis:
  secure:
    BINSTAR_TOKEN: nksVO6tYYjGCWqqlVeAghGv0F0T0SpM6qsAlf05dvIQXgzaTo8cN4/Ml44tEtfXtGKUJxxDgIgti2WdZkt46rEVWZ/Mzud5zsauzVcxachT7qRIAFcwekrWzrinzeIp8F5KjZv6RLKDTFf3TRBcqzV9tDxVvyxjqE1NqIRi8eil4eD65hoEs2Iwzjk8A/wvqhZvqvJ1yTLrlYwuIWzPpU24Q3NFSpxlqR8XXAS2Ql6BhRkzS3k+95yaBvdjyGnRzrqgNDiSnIRs9AEMxKJVUZN736HUnxluoRjdEqptq/jP455cO1wvs3Zu3h5HahYRu5TqZzV1RaDn1cqcRxbxgm3rtzQzkCRJHANsnvn0MR4Tv9/tp6hpCWn2e9jmW5J4HqE+V5+QU6pxhD+E3LgpmzrV72SKT2nXgA9fq4WQKie/r4mIPPMhpvUf4N7Xyo83VHBl6Ntg5jvFYRrhKUTtCZF/y51kEIOr8kF6hnRrjZCAXw97cbBE58TGy1BFFqC0y7RXmo1weenSeaq4ZEErdK/zpnN2UaDtW2Q4B05zAPRYf5cs/IY/bZ6v7nJRaQZ2i/B9pBR0iVO5fs2zpGpC+L5YmY9AYrZdB+0ZY2HBrMMnrnOUYuphPWwPld1gadeKHlx0NV3JvCgBGtNsVTjEYPyDep5hEMrJBfYJYF6CQ7BQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
