travis:
  secure:
    BINSTAR_TOKEN: e2MRturYLjg9RH0XCtDeVphIr228B5mMTanp0k+85mZnY3DYi9OSbYbk1AVkJHT4hJ9s5fZoY5MnEek7gVR43yOsgtUNYPSvBTXD/EGwp+YiFB+vIhduiMOKK6mcVn8nzBAPuq/pUMZBaG5LglxjA0NIx3XFfMfQ8EfxXoHG3eKU1nx5sNNnt8oDp2T8ioYEcqIY/UpKIz8k+H2gZZx8KtN/c6rLjPz1N8EcrGHBk0QpAVEwwl1Iztyu2SSU0RTQe14XjHYX7ee8D3f0gmni6xOLfjXjTZwUvMSaQ5YBFS2ji7d4QSuS18yXTnFx1kU/M6rCipuBxDNdymHcngxZPrXUchJKGGJLcXSadzOzF+N5MPAHTgrUegI/F2qfV6C+TeZsNpv+JHkVdJXZjUPWYElu6sWAVlZIVu/+89r0PyS0fTvONN3Cfpr58MvVUepoYuEfSXDZVAZzKsPUJyKowsNmVeA6kQPMeEy23TBo2TV3Vxep1h6bkl6qeFP2BWvIyWrGmW9ZGoqpPwUyXfpCPHs3aQHQOTVvGzXUTSREBl/ExN5JJ+/3W0daHMhDi8o1QsbMa8lVabSz38iWCfHFu5YxYMQZ7EiFeEmgahrPnwQ8FvBAreL41RIUF1lXeoZdp40iH8mnkgfdtNqouTsJPqEpt2GnkoS6X/zHJdyhod8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
